Repository cmpsc-481-s22-m1/CASTanet, pull requests merged in 2022-02, with the labels that each got.

#21 Func w docstring
  castanet/counter.py
  main.py
  test_files/funcdefs_test_file.py
  tests/test_counter.py
Labels: enhancement

#24 Count Function Parameters and Refactor Testing
  castanet/counter.py
  main.py
  tests/test_counter.py
Labels: enhancement, testing

#30 Modify Documentation to Add Commands and Library Functions
  .github/cspell.json
  README.md
  castanet.egg-info/PKG-INFO
  castanet.egg-info/SOURCES.txt
  castanet.egg-info/dependency_links.txt
  castanet.egg-info/entry_points.txt
  castanet.egg-info/requires.txt
  castanet.egg-info/top_level.txt
  castanet/counter.py
  main.py
  tests/test_counter.py
Labels: documentation

#31 CASTanet Release 2: Complete Features, Modify Documentation and Improve Testing
  .github/cspell.json
  README.md
  castanet/counter.py
  castanet/generate_trees.py
  main.py
  poetry.lock
  pyproject.toml
  test_files/classdefs.py
  test_files/funcdefs_test_file.py
  tests/test_counter.py
  tests/test_generator.py
Labels: bug, documentation, enhancement, testing
