Repository cmpsc-481-s22-m1/CASTanet, pull requests merged in 2022-01, with the labels that each got.

#1 Create background program and CLI for CASTanet
  README.md
  castanet.png
  castanet/counter.py
  castanet/generate_trees.py
  castanet/main.py
  castanet/practice_libcst.py
  poetry.lock
  pyproject.toml
Labels: Structure

#2 Document CASTanet
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/cspell.json
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#4 Function Definitions w/out Docstrings
  castanet/__init__.py
  castanet/counter.py
  castanet/generate_trees.py
  castanet/practice_libcst.py
  main.py
  pyproject.toml
  test_files/__init__.py
  test_files/funcdefs_test_file.py
  tests/test_counter.py
Labels: enhancement

#7 Modify Documentation and Improve Testing
  .vscode/settings.json
  README.md
  castanet/counter.py
  main.py
  tests/files_for_tests/comments.py
  tests/files_for_tests/functions.py
  tests/files_for_tests/if_statements.py
  tests/files_for_tests/looping.py
  tests/files_for_tests/small_test.py
  tests/test_counter.py
  tests/test_generator.py
Labels: bug, documentation, enhancement, testing

#5 If statements
  .DS_Store
  castanet/.DS_Store
  castanet/counter.py
  hello/.DS_Store
  main.py
  test_files/.DS_Store
  test_files/blackjack.py
  tests/.DS_Store
  tests/test_counter.py
Labels: enhancement

#6 Looping Constructs
  castanet/__init.py__
  castanet/counter.py
  main.py
  test_files/loops.py
  tests/test_counter.py
Labels: enhancement

#3 Comment
  castanet/counter.py
  hello/say_hello.py
  main.py
  poetry.lock
  tests/test_counter.py
Labels: enhancement

#8 Modify file structure and improve testing for final feature PR (sprint 1)
  .vscode/settings.json
  README.md
  castanet/__init.py__
  castanet/counter.py
  hello/say_hello.py
  main.py
  test_files/comments.py
  test_files/if_statements.py
  test_files/loops.py
  tests/files_for_tests/comments.py
  tests/files_for_tests/functions.py
  tests/files_for_tests/if_statements.py
  tests/files_for_tests/looping.py
  tests/files_for_tests/small_test.py
  tests/test_counter.py
  tests/test_generator.py
Labels: documentation, enhancement, testing

#10 Modify documentation of CASTanet for First Release
  .github/cspell.json
  CONTRIBUTING.md
  README.md
Labels: documentation

#9 CASTanet Release 1: Functions without docstrings, comments, if-statements, looping constructs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/cspell.json
  .gitignore
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  castanet.png
  castanet/__init__.py
  castanet/counter.py
  castanet/generate_trees.py
  main.py
  poetry.lock
  pyproject.toml
  test_files/__init__.py
  test_files/comments.py
  test_files/funcdefs_test_file.py
  test_files/if_statements.py
  test_files/loops.py
  tests/test_counter.py
  tests/test_generator.py
  tests/test_say_hello.py
Labels: documentation, enhancement, Structure, testing

#16 Count imports
  .DS_Store
  .github/cspell.json
  .gitignore
  CONTRIBUTING.md
  README.md
  castanet.egg-info/PKG-INFO
  castanet.egg-info/SOURCES.txt
  castanet.egg-info/dependency_links.txt
  castanet.egg-info/entry_points.txt
  castanet.egg-info/requires.txt
  castanet.egg-info/top_level.txt
  castanet/.DS_Store
  castanet/counter.py
  hello/.DS_Store
  hello/__init__.py
  hello/say_hello.py
  main.py
  pyproject.toml
  test_files/.DS_Store
  test_files/comments.py
  tests/.DS_Store
  tests/test_counter.py
  tests/test_say_hello.py
Labels: enhancement, testing
